# Les infos sur le site
site_name: Numériques et Sciences Informatiques Terminale
site_description: Cours de NSI en classe de terminale du lycée Hintermann-Afféjee
site_author: Fabrice NATIVEL

# Les éléments de la barre de navigation
nav:
- "<img src='https://fabricenativel.github.io/NSITerminale/images/icones/home.svg' width=16px height=16px>&thinsp; Accueil" :
    - index.md
- "<img src='https://fabricenativel.github.io/NSITerminale/images/icones/list-ordered-16.svg' width=16px height=16px>&thinsp; Liste des chapitres" :
      - "Progression" : progression.md
      - "C0-Révisions" : revisions.md
      - "C1-Récursivité" : recursivite.md
      - "C2-Bases de données et SQL" : sql.md
      - "C3-Processus" : processus.md
      - "C4-Diviser pour régner" : diviser.md
      - "C5-Notions de programmation orienté objet" : poo.md
      - "C6-Structures de données linéaires" : sl.md
      - "C7-Système sur puce" : puces.md
      - "C8-Arbres" : arbres.md
      - "C9-Schéma relationnel d'une base de données" : sgbd.md
      - "C10-Algorithmes sur les arbres" : algoarbre.md
      - "C11-Graphes" : graphes.md
      - "C12-Protocoles de routage" : routage.md
      - "C13-Recherche textuelle" : texte.md
      - "C14-Calculabilité, décidabilité" : calculabilite.md
      - "C15-Sécurisation des communications" : cryptage.md
- "<img src='https://fabricenativel.github.io/NSITerminale/images/icones/file-badge-16.svg' width=16px height=16px>&thinsp; Documents officiels" :
    - docs.md
- "<img src='https://fabricenativel.github.io/NSITerminale/images/icones/lightbulb.svg' width=16px height=16px>&thinsp; Projets" :
    - projets.md
- "<img src='https://fabricenativel.github.io/NSITerminale/images/icones/information.svg' width=16px height=16px>&thinsp; A propos" :
    - apropos.md
  



#Le thème du site
theme:
  name: material
  language: fr
  # Changement de l'icone du site (dans la barre de titre) les icones sont à chercher dans ~/.local/lib/python3.8/site-packages/material/.icons
  icon:
    logo: fontawesome/solid/dragon
  favicon : images/dragon.svg
  # Les couleurs, on utilise la palette par défaut avec qques tweaks via css (voir https://github.com/squidfunk/mkdocs-material/blob/master/src/assets/stylesheets/main/_colors.scss)
  palette: 
    scheme: default
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.superfences:          # Imbrication de blocs.
    # Exception pour code highlight (de façon à faire fonctionner mermaid)
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid

  - pymdownx.tabbed               # Volets glissants.  === "Mon volet"
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:            # Cases à cocher  - [ ]  et - [x]
        custom_checkbox:    true   #   avec cases d'origine
        clickable_checkbox: true    #   et cliquables.


  - attr_list
  # Permet l'utilisation d'abbréviation dans le fichier syntaxe *[abbr]: description (voir glossaire.md)
  - abbr
  # Permet l'insertion de fichiers dans le document à l'aide de la syntaxe --8<-- "includes/glossaire.md"
  - pymdownx.snippets
  # Admonitions et variantes (details : repliable, superfences : avec onglet)
  - admonition
  - pymdownx.details
  - pymdownx.keys:
      strict: false


plugins:
  - macros
  - search
  - mermaid2

extra_css:
  - stylesheets/fenarius.css

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid@8.7.0/dist/mermaid.min.js
  
