# Les infos sur le site
site_name: Numériques et Sciences Informatiques Terminale
site_description: Cours de NSI en classe de terminale du lycée Hintermann-Afféjee
site_author: Fabrice NATIVEL

# Les éléments de la barre de navigation
nav:
- "<img src='https://fabricenativel.github.io/NSITerminale/images/icones/home.svg' width=16px height=16px>&thinsp; Accueil" :
    - index.md
- "<img src='https://fabricenativel.github.io/NSITerminale/images/icones/list-ordered-16.svg' width=16px height=16px>&thinsp; Liste des chapitres" :
      - "Progression" : progression.md
      - "C0-Révisions" : revisions.md
      - "C1-Récursivité" : recursivite.md
      - "C2-Bases de données et SQL" : sql.md
      - "C3-Processus" : processus.md
      - "C4-Diviser pour régner" : diviser.md
      - "C5-Notions de programmation orienté objet" : poo.md
      - "C6-Structures de données linéaires" : sl.md
      - "C7-Système sur puce" : puces.md
      - "C8-Arbres" : arbres.md
      - "C9-Schéma relationnel d'une base de données" : sgbd.md
      - "C10-Algorithmes sur les arbres" : algoarbre.md
      - "C11-Graphes" : graphes.md
      - "C12-Protocoles de routage" : routage.md
      - "C13-Recherche textuelle" : texte.md
      - "C14-Calculabilité, décidabilité" : calculabilite.md
      - "C15-Sécurisation des communications" : cryptographie.md
- "<img src='https://fabricenativel.github.io/NSITerminale/images/icones/file-badge-16.svg' width=16px height=16px>&thinsp; Documents officiels" :
    - docs.md
- "<img src='https://fabricenativel.github.io/NSITerminale/images/icones/graduation-cap.svg' width=16px height=16px>&thinsp; Annales du Bac" :
    - index_annales.md
    - '2021': 
      - "Epreuves écrites" : Annales/2021/EE.md
      - "Corrigés épreuves écrites" :
        - "Etranger CL Sujet 2" : Annales/Corriges/21-EtrangerJ2.md
        - "Amérique du nord" : Annales/Corriges/21-Amerique.md
      - "Epreuves pratiques" : Annales/2021/EP.md
    - '2022': 
      - "Epreuves écrites" : Annales/2022/EE.md
      - "Epreuves pratiques" : Annales/2022/EP.md
      - "Corrigés épreuves pratiques":
        - "Sujet 1" : Annales/Corriges/2022-S01.md
        - "Sujet 2" : Annales/Corriges/2022-S02.md
        - "Sujet 3" : Annales/Corriges/2022-S03.md
        - "Sujet 4" : Annales/Corriges/2022-S04.md
        - "Sujet 5" : Annales/Corriges/2022-S05.md
        - "Sujet 6" : Annales/Corriges/2022-S06.md
        - "Sujet 7" : Annales/Corriges/2022-S07.md
        - "Sujet 8" : Annales/Corriges/2022-S08.md
        - "Sujet 9" : Annales/Corriges/2022-S09.md
        - "Sujet 10" : Annales/Corriges/2022-S10.md
        - "Sujet 11" : Annales/Corriges/2022-S11.md
        - "Sujet 12" : Annales/Corriges/2022-S12.md
        - "Sujet 13" : Annales/Corriges/2022-S13.md
        - "Sujet 14" : Annales/Corriges/2022-S14.md
        - "Sujet 15" : Annales/Corriges/2022-S15.md
        - "Sujet 16" : Annales/Corriges/2022-S16.md
        - "Sujet 17" : Annales/Corriges/2022-S17.md
        - "Sujet 18" : Annales/Corriges/2022-S18.md
        - "Sujet 19" : Annales/Corriges/2022-S19.md
        - "Sujet 20" : Annales/Corriges/2022-S20.md
        - "Sujet 21" : Annales/Corriges/2022-S21.md
        - "Sujet 22" : Annales/Corriges/2022-S22.md
        - "Sujet 23" : Annales/Corriges/2022-S23.md
        - "Sujet 24" : Annales/Corriges/2022-S24.md
        - "Sujet 25" : Annales/Corriges/2022-S25.md
        - "Sujet 26" : Annales/Corriges/2022-S26.md
        - "Sujet 27" : Annales/Corriges/2022-S27.md
        - "Sujet 28" : Annales/Corriges/2022-S28.md
        - "Sujet 29" : Annales/Corriges/2022-S29.md
        - "Sujet 30" : Annales/Corriges/2022-S30.md
        - "Sujet 31" : Annales/Corriges/2022-S31.md
        - "Sujet 32" : Annales/Corriges/2022-S32.md
        - "Sujet 33" : Annales/Corriges/2022-S33.md
        - "Sujet 34" : Annales/Corriges/2022-S34.md
        - "Sujet 35" : Annales/Corriges/2022-S35.md
        - "Sujet 36" : Annales/Corriges/2022-S36.md
        - "Sujet 37" : Annales/Corriges/2022-S37.md
        - "Sujet 38" : Annales/Corriges/2022-S38.md
        - "Sujet 39" : Annales/Corriges/2022-S39.md
        - "Sujet 40" : Annales/Corriges/2022-S40.md
- "<img src='https://fabricenativel.github.io/NSITerminale/images/icones/lightbulb.svg' width=16px height=16px>&thinsp; Projets" :
    - projets.md
- "<img src='https://fabricenativel.github.io/NSITerminale/images/icones/links.svg' width=16px height=16px>&thinsp; Liens" :
    - liens.md
- "<img src='https://fabricenativel.github.io/NSITerminale/images/icones/information.svg' width=16px height=16px>&thinsp; A propos" :
    - apropos.md
  



#Le thème du site
theme:
  name: material
  language: fr
  # Changement de l'icone du site (dans la barre de titre) les icones sont à chercher dans ~/.local/lib/python3.8/site-packages/material/.icons
  icon:
    logo: fontawesome/solid/dragon
  favicon : images/dragon.svg
  # Les couleurs, on utilise la palette par défaut avec qques tweaks via css (voir https://github.com/squidfunk/mkdocs-material/blob/master/src/assets/stylesheets/main/_colors.scss)
  palette: 
    scheme: default
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.annotate 
    - navigation.expand

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.superfences:          # Imbrication de blocs.
    # Exception pour code highlight (de façon à faire fonctionner mermaid)
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid

  - pymdownx.tabbed:
      alternate_style: true          # Volets glissants.  === "Mon volet"
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:            # Cases à cocher  - [ ]  et - [x]
        custom_checkbox:    true   #   avec cases d'origine
        clickable_checkbox: true    #   et cliquables.


  - attr_list
  # Permet l'utilisation d'abbréviation dans le fichier syntaxe *[abbr]: description (voir glossaire.md)
  - abbr
  # Permet l'insertion de fichiers dans le document à l'aide de la syntaxe --8<-- "includes/glossaire.md"
  - pymdownx.snippets
  # Admonitions et variantes (details : repliable, superfences : avec onglet)
  - admonition
  - pymdownx.details
  - pymdownx.keys:
      strict: false


plugins:
  - search
  - mermaid2
  - macros


extra_css:
  - stylesheets/fenarius.css

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid@8.7.0/dist/mermaid.min.js
  
