def insertion(element,liste):
    '''Insère element dans  liste (qui est déjà triée)'''
    liste........(element)
    pos = ......
    while pos>... and liste[pos]<.....:
        liste[pos],liste[pos-1] =  ........... , ............ 
        pos = ......