def dichotomie(liste,element):
    ''' recherche element dans liste en utilisant la recherche dichotomique'''
    debut = ...
    fin = ....
    while debut<=fin:
        milieu = ......
        if liste[milieu]==element:
            return ......
        if liste[milieu]>element:
            fin = .....
        else:
            debut = ....
    return ....
