def rendre_monnaie(s,pieces):
    indice_piece = .......
    a_rendre = .....
    while s != ...:
        if .... <= s:
            s .....
            a_rendre.......
        else:
            indice_piece .....
    return a_rendre

print(rendre_monnaie(128,[1,2,5,10,20,50]))
        